# Generated by Django 5.0.6 on 2024-08-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJoyeria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
    ]
