# Generated by Django 5.0.6 on 2024-08-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJoyeria', '0002_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('asignado', 'Asignado'), ('terminado', 'Terminado')], default='asignado', max_length=10),
        ),
    ]
